### ISSUE TITLE
Esta linea no es necesaria...

### ISSUE THREAD

**Issue by evolentini** [PabloFolino/leds#1]
Todos los leds inician apagados

https://github.com/PabloFolino/leds/blob/7d99d67cb8d0872f56ecff27510da22a5e24d5e1/test/test_leds.c#L82

**Comment by PabloFolino** [comment]
Si Esteban, esa línea me olvidé de borrarla.   Saludos Pablo

**Comment by evolentini** [comment]
En función de las correcciones se cambio la nota del TP3
