### ISSUE TITLE
Se puede refactorizar el condigo

### ISSUE THREAD

**Issue by evolentini** [PabloFolino/leds#3]
El código de esta función

https://github.com/PabloFolino/leds/blob/7d99d67cb8d0872f56ecff27510da22a5e24d5e1/src/leds.c#L39-L47

se puede refactorizar de la siguiente forma

```c
bool Leds_Test(uint8_t led ){
    return 0 != (*direccion & LedToMask(led));
}
```

**Comment by PabloFolino** [comment]
Si profe, corregido.
